/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWidgetjsRouteImport } from './routes/api/widgetjs'
import { Route as ApiPushRouteImport } from './routes/api/push'
import { Route as ApiPublicWidgetRouteImport } from './routes/api/public/widget'
import { Route as ApiPublicRespondRouteImport } from './routes/api/public/respond'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetjsRoute = ApiWidgetjsRouteImport.update({
  id: '/api/widgetjs',
  path: '/api/widgetjs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetRoute = ApiPublicWidgetRouteImport.update({
  id: '/api/public/widget',
  path: '/api/public/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRespondRoute = ApiPublicRespondRouteImport.update({
  id: '/api/public/respond',
  path: '/api/public/respond',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/test': typeof TestRoute
  '/api/push': typeof ApiPushRoute
  '/api/widgetjs': typeof ApiWidgetjsRoute
  '/api/public/respond': typeof ApiPublicRespondRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/test': typeof TestRoute
  '/api/push': typeof ApiPushRoute
  '/api/widgetjs': typeof ApiWidgetjsRoute
  '/api/public/respond': typeof ApiPublicRespondRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/test': typeof TestRoute
  '/api/push': typeof ApiPushRoute
  '/api/widgetjs': typeof ApiWidgetjsRoute
  '/api/public/respond': typeof ApiPublicRespondRoute
  '/api/public/widget': typeof ApiPublicWidgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/test'
    | '/api/push'
    | '/api/widgetjs'
    | '/api/public/respond'
    | '/api/public/widget'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/test'
    | '/api/push'
    | '/api/widgetjs'
    | '/api/public/respond'
    | '/api/public/widget'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/test'
    | '/api/push'
    | '/api/widgetjs'
    | '/api/public/respond'
    | '/api/public/widget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  TestRoute: typeof TestRoute
  ApiPushRoute: typeof ApiPushRoute
  ApiWidgetjsRoute: typeof ApiWidgetjsRoute
  ApiPublicRespondRoute: typeof ApiPublicRespondRoute
  ApiPublicWidgetRoute: typeof ApiPublicWidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widgetjs': {
      id: '/api/widgetjs'
      path: '/api/widgetjs'
      fullPath: '/api/widgetjs'
      preLoaderRoute: typeof ApiWidgetjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget': {
      id: '/api/public/widget'
      path: '/api/public/widget'
      fullPath: '/api/public/widget'
      preLoaderRoute: typeof ApiPublicWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/respond': {
      id: '/api/public/respond'
      path: '/api/public/respond'
      fullPath: '/api/public/respond'
      preLoaderRoute: typeof ApiPublicRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  TestRoute: TestRoute,
  ApiPushRoute: ApiPushRoute,
  ApiWidgetjsRoute: ApiWidgetjsRoute,
  ApiPublicRespondRoute: ApiPublicRespondRoute,
  ApiPublicWidgetRoute: ApiPublicWidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
